version: '3.8'

services:
  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"   # Web UI
      - "5051:5051"   # MCP Server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
